// Central mock data for CinePilot AI - placeholder for future Firestore integration
export type AgentStatus = "active" | "idle" | "thinking" | "error";

export interface Agent {
  id: string;
  name: string;
  role: string;
  emoji: string;
  status: AgentStatus;
  confidence: number;
  currentTask: string;
  lastAction: string;
  progress: number;
  tools: string[];
  color: string;
}

export const agents: Agent[] = [
  {
    id: "producer",
    name: "Producer Agent",
    role: "Orchestrator",
    emoji: "🎬",
    status: "active",
    confidence: 98,
    currentTask: "Coordinating scene 12 reschedule across 4 agents",
    lastAction: "Delegated call sheet generation to Scheduling Agent",
    progress: 72,
    tools: ["delegate", "monitor", "resolve_conflict"],
    color: "oklch(0.72 0.19 305)",
  },
  {
    id: "script",
    name: "Script Analyst",
    role: "Script Breakdown",
    emoji: "✍️",
    status: "active",
    confidence: 94,
    currentTask: "Parsing Act III revisions from 'Neon Skyline v4.2'",
    lastAction: "Extracted 42 scenes, 18 speaking roles, 9 locations",
    progress: 88,
    tools: ["vertex_ai.gemini", "pdf_parse", "scene_split"],
    color: "oklch(0.70 0.17 220)",
  },
  {
    id: "schedule",
    name: "Scheduling Agent",
    role: "Optimizer",
    emoji: "📅",
    status: "thinking",
    confidence: 91,
    currentTask: "Minimizing location swaps for week 3 shoot block",
    lastAction: "Generated 3 candidate schedules, ranking by cost",
    progress: 54,
    tools: ["constraint_solver", "calendar_api", "weather_api"],
    color: "oklch(0.75 0.17 160)",
  },
  {
    id: "budget",
    name: "Budget Agent",
    role: "Cost Analyst",
    emoji: "💰",
    status: "active",
    confidence: 96,
    currentTask: "Flagging equipment rental overrun on Alexa Mini LF",
    lastAction: "Suggested Sony Venice 2 as $18k/day alternative",
    progress: 63,
    tools: ["cost_estimate", "vendor_db", "forecast"],
    color: "oklch(0.80 0.17 75)",
  },
  {
    id: "shots",
    name: "Shot List Agent",
    role: "Cinematography",
    emoji: "🎥",
    status: "idle",
    confidence: 89,
    currentTask: "Awaiting director notes on scene 7 (rooftop chase)",
    lastAction: "Drafted 14-shot list for scene 6 dialogue",
    progress: 100,
    tools: ["storyboard_gen", "lens_kit", "coverage_plan"],
    color: "oklch(0.72 0.16 265)",
  },
  {
    id: "costume",
    name: "Costume Agent",
    role: "Wardrobe",
    emoji: "👕",
    status: "active",
    confidence: 87,
    currentTask: "Cross-referencing continuity for hero jacket across 11 scenes",
    lastAction: "Ordered 3 backup shirts for rain sequence",
    progress: 41,
    tools: ["continuity_check", "vendor_order", "fit_schedule"],
    color: "oklch(0.72 0.18 340)",
  },
  {
    id: "props",
    name: "Props Agent",
    role: "Inventory",
    emoji: "📦",
    status: "idle",
    confidence: 92,
    currentTask: "Prop manifest ready for Monday",
    lastAction: "Sourced 1970s rotary phone for scene 22",
    progress: 100,
    tools: ["inventory_db", "vendor_order", "continuity_check"],
    color: "oklch(0.75 0.14 190)",
  },
  {
    id: "location",
    name: "Location Agent",
    role: "Logistics",
    emoji: "📍",
    status: "thinking",
    confidence: 84,
    currentTask: "Re-routing crew transport around bridge closure",
    lastAction: "Confirmed permit for Downtown LA rooftop",
    progress: 33,
    tools: ["maps_api", "permit_db", "travel_plan"],
    color: "oklch(0.70 0.18 240)",
  },
  {
    id: "risk",
    name: "Risk Analysis Agent",
    role: "Sentinel",
    emoji: "⚠️",
    status: "active",
    confidence: 90,
    currentTask: "Monitoring forecast — 60% rain risk Thursday",
    lastAction: "Escalated actor conflict for scene 19 to Producer",
    progress: 78,
    tools: ["weather_api", "conflict_detect", "budget_watch"],
    color: "oklch(0.68 0.22 25)",
  },
];

export const productions = [
  {
    id: "p1",
    title: "Neon Skyline",
    status: "In Production",
    progress: 62,
    genre: "Sci-Fi Thriller",
    director: "Ava Chen",
    shootDays: 34,
    completedDays: 21,
    budget: 4_800_000,
    spent: 2_976_000,
    crew: 84,
    scenes: 142,
    script: "Neon Skyline v4.2.pdf",
    scriptStatus: "Parsed",
    revisions: 4,
    lastUpdate: "2h ago",
  },
  {
    id: "p2",
    title: "Harbor Light",
    status: "Pre-Production",
    progress: 24,
    genre: "Drama",
    director: "Marcus Reid",
    shootDays: 22,
    completedDays: 0,
    budget: 1_200_000,
    spent: 288_000,
    crew: 42,
    scenes: 78,
    script: "Harbor Light v2.0.docx",
    scriptStatus: "Analyzing",
    revisions: 2,
    lastUpdate: "5h ago",
  },
  {
    id: "p3",
    title: "The Cartographer",
    status: "Post-Production",
    progress: 91,
    genre: "Documentary",
    director: "Priya Anand",
    shootDays: 18,
    completedDays: 18,
    budget: 650_000,
    spent: 591_500,
    crew: 24,
    scenes: 46,
    script: "Cartographer_final.txt",
    scriptStatus: "Parsed",
    revisions: 7,
    lastUpdate: "1d ago",
  },
  {
    id: "p4",
    title: "Silver & Salt",
    status: "Development",
    progress: 8,
    genre: "Period Drama",
    director: "Elena Vargas",
    shootDays: 0,
    completedDays: 0,
    budget: 2_100_000,
    spent: 42_000,
    crew: 12,
    scenes: 0,
    script: "silver_salt_treatment.pdf",
    scriptStatus: "Pending",
    revisions: 1,
    lastUpdate: "3d ago",
  },
];

export const progressData = [
  { day: "Mon", planned: 5, actual: 5 },
  { day: "Tue", planned: 6, actual: 7 },
  { day: "Wed", planned: 5, actual: 4 },
  { day: "Thu", planned: 6, actual: 6 },
  { day: "Fri", planned: 7, actual: 8 },
  { day: "Sat", planned: 4, actual: 5 },
  { day: "Sun", planned: 3, actual: 3 },
];

export const budgetBreakdown = [
  { name: "Equipment", value: 1_150_000, color: "oklch(0.72 0.19 305)" },
  { name: "Talent", value: 1_420_000, color: "oklch(0.70 0.17 220)" },
  { name: "Locations", value: 680_000, color: "oklch(0.75 0.17 160)" },
  { name: "Catering", value: 210_000, color: "oklch(0.80 0.17 75)" },
  { name: "Transportation", value: 340_000, color: "oklch(0.68 0.22 25)" },
  { name: "Insurance", value: 280_000, color: "oklch(0.72 0.14 265)" },
  { name: "Marketing", value: 520_000, color: "oklch(0.72 0.18 340)" },
  { name: "Contingency", value: 200_000, color: "oklch(0.75 0.14 190)" },
];

export const spendingTrend = [
  { week: "W1", spent: 120, forecast: 140 },
  { week: "W2", spent: 260, forecast: 280 },
  { week: "W3", spent: 420, forecast: 430 },
  { week: "W4", spent: 610, forecast: 590 },
  { week: "W5", spent: 830, forecast: 760 },
  { week: "W6", spent: 1080, forecast: 950 },
  { week: "W7", spent: 1360, forecast: 1180 },
  { week: "W8", spent: 1690, forecast: 1440 },
];

export const crewUtilization = [
  { day: "Mon", utilization: 78 },
  { day: "Tue", utilization: 92 },
  { day: "Wed", utilization: 85 },
  { day: "Thu", utilization: 96 },
  { day: "Fri", utilization: 88 },
  { day: "Sat", utilization: 64 },
  { day: "Sun", utilization: 22 },
];

export const shootDays = [
  {
    date: "2026-07-22",
    scenes: ["Sc. 12", "Sc. 13"],
    location: "Downtown LA — Rooftop",
    actors: ["Elena K.", "Marcus V."],
    crew: 42,
    equipment: "Alexa Mini LF, DJI Ronin 4D",
    weather: "Clear, 78°F",
    duration: "12h",
    conflict: false,
  },
  {
    date: "2026-07-23",
    scenes: ["Sc. 14", "Sc. 15", "Sc. 16"],
    location: "Warehouse District",
    actors: ["Elena K.", "Devon P.", "Sana R."],
    crew: 48,
    equipment: "Sony Venice 2, Steadicam",
    weather: "Partly cloudy",
    duration: "14h",
    conflict: true,
  },
  {
    date: "2026-07-24",
    scenes: ["Sc. 17"],
    location: "Griffith Observatory",
    actors: ["Marcus V."],
    crew: 28,
    equipment: "RED Komodo",
    weather: "60% rain risk",
    duration: "8h",
    conflict: true,
  },
  {
    date: "2026-07-25",
    scenes: ["Sc. 18", "Sc. 19"],
    location: "Sound Stage 4",
    actors: ["Elena K.", "Marcus V.", "Devon P."],
    crew: 52,
    equipment: "Full lighting rig, motion control",
    weather: "Interior",
    duration: "13h",
    conflict: false,
  },
  {
    date: "2026-07-26",
    scenes: ["Sc. 20"],
    location: "Malibu Beach",
    actors: ["Sana R.", "Jules T."],
    crew: 34,
    equipment: "Drone kit, waterproof housing",
    weather: "Sunny, 82°F",
    duration: "10h",
    conflict: false,
  },
];

export const notifications = [
  {
    id: "n1",
    type: "risk",
    title: "Weather risk detected",
    message: "60% chance of rain Thursday for Griffith Observatory shoot. Consider indoor backup.",
    time: "12m ago",
    agent: "Risk Analysis Agent",
    unread: true,
  },
  {
    id: "n2",
    type: "budget",
    title: "Equipment rental over budget",
    message: "Alexa Mini LF exceeds category by $12,400. Sony Venice 2 suggested as alternative.",
    time: "34m ago",
    agent: "Budget Agent",
    unread: true,
  },
  {
    id: "n3",
    type: "script",
    title: "Script revision uploaded",
    message: "Neon Skyline v4.2 parsed — 3 new scenes, 1 removed. Impact analysis ready.",
    time: "1h ago",
    agent: "Script Analyst",
    unread: true,
  },
  {
    id: "n4",
    type: "conflict",
    title: "Actor scheduling conflict",
    message: "Marcus V. double-booked on July 23. Producer Agent proposed a swap with Sc. 15.",
    time: "2h ago",
    agent: "Scheduling Agent",
    unread: false,
  },
  {
    id: "n5",
    type: "prop",
    title: "Missing prop flagged",
    message: "1970s rotary phone for Sc. 22 not confirmed. Vendor order placed automatically.",
    time: "3h ago",
    agent: "Props Agent",
    unread: false,
  },
  {
    id: "n6",
    type: "done",
    title: "Call sheet ready",
    message: "Tomorrow's call sheet generated and distributed to 42 crew members.",
    time: "5h ago",
    agent: "Producer Agent",
    unread: false,
  },
];

export const reports = [
  { id: "r1", name: "Scene Breakdown", description: "Full scene-by-scene analysis with cast, props, and locations", updated: "2h ago" },
  { id: "r2", name: "Shooting Order", description: "Optimized production order minimizing location and cast conflicts", updated: "4h ago" },
  { id: "r3", name: "Daily Call Sheet", description: "Tomorrow's call sheet with crew, cast, and equipment", updated: "5h ago" },
  { id: "r4", name: "Crew Report", description: "Utilization, overtime, and availability across all departments", updated: "1d ago" },
  { id: "r5", name: "Budget Report", description: "Actual vs. planned spend with variance and forecast", updated: "6h ago" },
  { id: "r6", name: "Production Summary", description: "Executive summary of progress across all active productions", updated: "1d ago" },
  { id: "r7", name: "Risk Assessment", description: "Weather, budget, schedule, and resource risks flagged by AI", updated: "12m ago" },
];

export const agentActivity = [
  { time: "09:14", agent: "Producer Agent", action: "Delegated schedule optimization to Scheduling Agent", status: "done" },
  { time: "09:18", agent: "Scheduling Agent", action: "Generated 3 candidate schedules for week 3", status: "done" },
  { time: "09:24", agent: "Budget Agent", action: "Evaluated cost impact of schedule variants", status: "done" },
  { time: "09:31", agent: "Risk Analysis Agent", action: "Flagged weather risk in variant A", status: "done" },
  { time: "09:42", agent: "Producer Agent", action: "Selected variant B, published to crew", status: "done" },
  { time: "10:03", agent: "Script Analyst", action: "Parsing Neon Skyline v4.2 revisions", status: "running" },
  { time: "10:08", agent: "Location Agent", action: "Re-routing transport around bridge closure", status: "running" },
];
