import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { Download, FileJson, FileSpreadsheet, FileText } from "lucide-react";
import { PageHeader, SectionCard } from "@/components/section-card";
import { reports } from "@/lib/mock-data";
import { toast } from "sonner";

export const Route = createFileRoute("/reports")({
  component: Reports,
  head: () => ({
    meta: [
      { title: "Reports — CinePilot AI" },
      { name: "description", content: "Auto-generated production reports, exportable to PDF, CSV, JSON." },
    ],
  }),
});

function Reports() {
  return (
    <>
      <PageHeader
        title="Reports"
        subtitle="Every report is auto-generated by CinePilot and refreshed as production data changes."
      />

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {reports.map((r, i) => (
          <motion.div
            key={r.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.04 }}
            className="glass rounded-2xl p-5 hover:border-primary/40 transition"
          >
            <div className="flex items-start justify-between">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/15 text-primary">
                <FileText className="h-5 w-5" />
              </div>
              <span className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Updated {r.updated}
              </span>
            </div>
            <div className="mt-3 font-display text-base font-semibold">{r.name}</div>
            <p className="mt-1 text-xs text-muted-foreground">{r.description}</p>

            <div className="mt-4 flex gap-1.5">
              <button
                onClick={() => toast.success(`${r.name} exported to PDF`)}
                className="flex-1 inline-flex items-center justify-center gap-1 rounded-lg border border-border/60 bg-white/5 px-2 py-1.5 text-[11px] hover:bg-white/10 transition"
              >
                <Download className="h-3 w-3" /> PDF
              </button>
              <button
                onClick={() => toast.success(`${r.name} exported to CSV`)}
                className="flex-1 inline-flex items-center justify-center gap-1 rounded-lg border border-border/60 bg-white/5 px-2 py-1.5 text-[11px] hover:bg-white/10 transition"
              >
                <FileSpreadsheet className="h-3 w-3" /> CSV
              </button>
              <button
                onClick={() => toast.success(`${r.name} exported to JSON`)}
                className="flex-1 inline-flex items-center justify-center gap-1 rounded-lg border border-border/60 bg-white/5 px-2 py-1.5 text-[11px] hover:bg-white/10 transition"
              >
                <FileJson className="h-3 w-3" /> JSON
              </button>
            </div>
          </motion.div>
        ))}
      </div>

      <SectionCard
        className="mt-6"
        title="Google Cloud pipeline"
        subtitle="Reports are rendered by Cloud Run and stored in Cloud Storage"
      >
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-xs">
          {[
            ["Vertex AI", "Composes narrative & summary sections"],
            ["Cloud Run", "Renders PDF, CSV, JSON in parallel"],
            ["Cloud Storage", "gs://cinepilot-reports"],
            ["Firestore", "reports/ collection metadata"],
          ].map(([k, v]) => (
            <div key={k} className="rounded-lg border border-border/40 bg-white/5 p-3">
              <div className="text-primary font-medium">{k}</div>
              <div className="mt-1 text-muted-foreground">{v}</div>
            </div>
          ))}
        </div>
      </SectionCard>
    </>
  );
}
