/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActorRouteRouteImport } from './routes/_actor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedCollaborationRouteImport } from './routes/_authenticated/collaboration'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedArchitectureRouteImport } from './routes/_authenticated/architecture'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ActorActorIndexRouteImport } from './routes/_actor/actor/index'
import { Route as ActorActorSettingsRouteImport } from './routes/_actor/actor/settings'
import { Route as ActorActorScriptsRouteImport } from './routes/_actor/actor/scripts'
import { Route as ActorActorScheduleRouteImport } from './routes/_actor/actor/schedule'
import { Route as ActorActorProfileRouteImport } from './routes/_actor/actor/profile'
import { Route as ActorActorNotificationsRouteImport } from './routes/_actor/actor/notifications'
import { Route as ActorActorNotesRouteImport } from './routes/_actor/actor/notes'
import { Route as ActorActorMoviesRouteImport } from './routes/_actor/actor/movies'
import { Route as ActorActorMessagesRouteImport } from './routes/_actor/actor/messages'
import { Route as ActorActorDocumentsRouteImport } from './routes/_actor/actor/documents'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorRouteRoute = ActorRouteRouteImport.update({
  id: '/_actor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollaborationRoute =
  AuthenticatedCollaborationRouteImport.update({
    id: '/collaboration',
    path: '/collaboration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchitectureRoute =
  AuthenticatedArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ActorActorIndexRoute = ActorActorIndexRouteImport.update({
  id: '/actor/',
  path: '/actor/',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorSettingsRoute = ActorActorSettingsRouteImport.update({
  id: '/actor/settings',
  path: '/actor/settings',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorScriptsRoute = ActorActorScriptsRouteImport.update({
  id: '/actor/scripts',
  path: '/actor/scripts',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorScheduleRoute = ActorActorScheduleRouteImport.update({
  id: '/actor/schedule',
  path: '/actor/schedule',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorProfileRoute = ActorActorProfileRouteImport.update({
  id: '/actor/profile',
  path: '/actor/profile',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorNotificationsRoute = ActorActorNotificationsRouteImport.update({
  id: '/actor/notifications',
  path: '/actor/notifications',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorNotesRoute = ActorActorNotesRouteImport.update({
  id: '/actor/notes',
  path: '/actor/notes',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorMoviesRoute = ActorActorMoviesRouteImport.update({
  id: '/actor/movies',
  path: '/actor/movies',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorMessagesRoute = ActorActorMessagesRouteImport.update({
  id: '/actor/messages',
  path: '/actor/messages',
  getParentRoute: () => ActorRouteRoute,
} as any)
const ActorActorDocumentsRoute = ActorActorDocumentsRouteImport.update({
  id: '/actor/documents',
  path: '/actor/documents',
  getParentRoute: () => ActorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/architecture': typeof AuthenticatedArchitectureRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/collaboration': typeof AuthenticatedCollaborationRoute
  '/command': typeof AuthenticatedCommandRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/actor/documents': typeof ActorActorDocumentsRoute
  '/actor/messages': typeof ActorActorMessagesRoute
  '/actor/movies': typeof ActorActorMoviesRoute
  '/actor/notes': typeof ActorActorNotesRoute
  '/actor/notifications': typeof ActorActorNotificationsRoute
  '/actor/profile': typeof ActorActorProfileRoute
  '/actor/schedule': typeof ActorActorScheduleRoute
  '/actor/scripts': typeof ActorActorScriptsRoute
  '/actor/settings': typeof ActorActorSettingsRoute
  '/actor/': typeof ActorActorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/architecture': typeof AuthenticatedArchitectureRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/collaboration': typeof AuthenticatedCollaborationRoute
  '/command': typeof AuthenticatedCommandRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/actor/documents': typeof ActorActorDocumentsRoute
  '/actor/messages': typeof ActorActorMessagesRoute
  '/actor/movies': typeof ActorActorMoviesRoute
  '/actor/notes': typeof ActorActorNotesRoute
  '/actor/notifications': typeof ActorActorNotificationsRoute
  '/actor/profile': typeof ActorActorProfileRoute
  '/actor/schedule': typeof ActorActorScheduleRoute
  '/actor/scripts': typeof ActorActorScriptsRoute
  '/actor/settings': typeof ActorActorSettingsRoute
  '/actor': typeof ActorActorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_actor': typeof ActorRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/architecture': typeof AuthenticatedArchitectureRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/collaboration': typeof AuthenticatedCollaborationRoute
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_actor/actor/documents': typeof ActorActorDocumentsRoute
  '/_actor/actor/messages': typeof ActorActorMessagesRoute
  '/_actor/actor/movies': typeof ActorActorMoviesRoute
  '/_actor/actor/notes': typeof ActorActorNotesRoute
  '/_actor/actor/notifications': typeof ActorActorNotificationsRoute
  '/_actor/actor/profile': typeof ActorActorProfileRoute
  '/_actor/actor/schedule': typeof ActorActorScheduleRoute
  '/_actor/actor/scripts': typeof ActorActorScriptsRoute
  '/_actor/actor/settings': typeof ActorActorSettingsRoute
  '/_actor/actor/': typeof ActorActorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/architecture'
    | '/budget'
    | '/collaboration'
    | '/command'
    | '/dashboard'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/schedule'
    | '/actor/documents'
    | '/actor/messages'
    | '/actor/movies'
    | '/actor/notes'
    | '/actor/notifications'
    | '/actor/profile'
    | '/actor/schedule'
    | '/actor/scripts'
    | '/actor/settings'
    | '/actor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/architecture'
    | '/budget'
    | '/collaboration'
    | '/command'
    | '/dashboard'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/schedule'
    | '/actor/documents'
    | '/actor/messages'
    | '/actor/movies'
    | '/actor/notes'
    | '/actor/notifications'
    | '/actor/profile'
    | '/actor/schedule'
    | '/actor/scripts'
    | '/actor/settings'
    | '/actor'
  id:
    | '__root__'
    | '/'
    | '/_actor'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/agents'
    | '/_authenticated/architecture'
    | '/_authenticated/budget'
    | '/_authenticated/collaboration'
    | '/_authenticated/command'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/schedule'
    | '/_actor/actor/documents'
    | '/_actor/actor/messages'
    | '/_actor/actor/movies'
    | '/_actor/actor/notes'
    | '/_actor/actor/notifications'
    | '/_actor/actor/profile'
    | '/_actor/actor/schedule'
    | '/_actor/actor/scripts'
    | '/_actor/actor/settings'
    | '/_actor/actor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorRouteRoute: typeof ActorRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_actor': {
      id: '/_actor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ActorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collaboration': {
      id: '/_authenticated/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof AuthenticatedCollaborationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/architecture': {
      id: '/_authenticated/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof AuthenticatedArchitectureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_actor/actor/': {
      id: '/_actor/actor/'
      path: '/actor'
      fullPath: '/actor/'
      preLoaderRoute: typeof ActorActorIndexRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/settings': {
      id: '/_actor/actor/settings'
      path: '/actor/settings'
      fullPath: '/actor/settings'
      preLoaderRoute: typeof ActorActorSettingsRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/scripts': {
      id: '/_actor/actor/scripts'
      path: '/actor/scripts'
      fullPath: '/actor/scripts'
      preLoaderRoute: typeof ActorActorScriptsRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/schedule': {
      id: '/_actor/actor/schedule'
      path: '/actor/schedule'
      fullPath: '/actor/schedule'
      preLoaderRoute: typeof ActorActorScheduleRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/profile': {
      id: '/_actor/actor/profile'
      path: '/actor/profile'
      fullPath: '/actor/profile'
      preLoaderRoute: typeof ActorActorProfileRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/notifications': {
      id: '/_actor/actor/notifications'
      path: '/actor/notifications'
      fullPath: '/actor/notifications'
      preLoaderRoute: typeof ActorActorNotificationsRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/notes': {
      id: '/_actor/actor/notes'
      path: '/actor/notes'
      fullPath: '/actor/notes'
      preLoaderRoute: typeof ActorActorNotesRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/movies': {
      id: '/_actor/actor/movies'
      path: '/actor/movies'
      fullPath: '/actor/movies'
      preLoaderRoute: typeof ActorActorMoviesRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/messages': {
      id: '/_actor/actor/messages'
      path: '/actor/messages'
      fullPath: '/actor/messages'
      preLoaderRoute: typeof ActorActorMessagesRouteImport
      parentRoute: typeof ActorRouteRoute
    }
    '/_actor/actor/documents': {
      id: '/_actor/actor/documents'
      path: '/actor/documents'
      fullPath: '/actor/documents'
      preLoaderRoute: typeof ActorActorDocumentsRouteImport
      parentRoute: typeof ActorRouteRoute
    }
  }
}

interface ActorRouteRouteChildren {
  ActorActorDocumentsRoute: typeof ActorActorDocumentsRoute
  ActorActorMessagesRoute: typeof ActorActorMessagesRoute
  ActorActorMoviesRoute: typeof ActorActorMoviesRoute
  ActorActorNotesRoute: typeof ActorActorNotesRoute
  ActorActorNotificationsRoute: typeof ActorActorNotificationsRoute
  ActorActorProfileRoute: typeof ActorActorProfileRoute
  ActorActorScheduleRoute: typeof ActorActorScheduleRoute
  ActorActorScriptsRoute: typeof ActorActorScriptsRoute
  ActorActorSettingsRoute: typeof ActorActorSettingsRoute
  ActorActorIndexRoute: typeof ActorActorIndexRoute
}

const ActorRouteRouteChildren: ActorRouteRouteChildren = {
  ActorActorDocumentsRoute: ActorActorDocumentsRoute,
  ActorActorMessagesRoute: ActorActorMessagesRoute,
  ActorActorMoviesRoute: ActorActorMoviesRoute,
  ActorActorNotesRoute: ActorActorNotesRoute,
  ActorActorNotificationsRoute: ActorActorNotificationsRoute,
  ActorActorProfileRoute: ActorActorProfileRoute,
  ActorActorScheduleRoute: ActorActorScheduleRoute,
  ActorActorScriptsRoute: ActorActorScriptsRoute,
  ActorActorSettingsRoute: ActorActorSettingsRoute,
  ActorActorIndexRoute: ActorActorIndexRoute,
}

const ActorRouteRouteWithChildren = ActorRouteRoute._addFileChildren(
  ActorRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedArchitectureRoute: typeof AuthenticatedArchitectureRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCollaborationRoute: typeof AuthenticatedCollaborationRoute
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedArchitectureRoute: AuthenticatedArchitectureRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCollaborationRoute: AuthenticatedCollaborationRoute,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorRouteRoute: ActorRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
